### ISSUE TITLE
Failed to execute goal org.glassfish.hk2:config-generator:2.4.0-b24:generate-injectors

### ISSUE THREAD

**Issue by puntogil** [hk2-project/hk2#11]
h
any ideas?
thanks in advance

[ERROR] Failed to execute goal org.glassfish.hk2:config-generator:2.4.0-b24:generate-injectors (default) on project config-types: Unable to create directory /builddir/build/BUILD/hk2-hk2-parent-2.4.0-b24/hk2-configuration/persistence/hk2-xml-dom/config-types/target/generated-sources/hk2-config-generator/src/main/java -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.glassfish.hk2:config-generator:2.4.0-b24:generate-injectors (default) on project config-types: Unable to create directory /builddir/build/BUILD/hk2-hk2-parent-2.4.0-b24/hk2-configuration/persistence/hk2-xml-dom/config-types/target/generated-sources/hk2-config-generator/src/main/java
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to create directory /builddir/build/BUILD/hk2-hk2-parent-2.4.0-b24/hk2-configuration/persistence/hk2-xml-dom/config-types/target/generated-sources/hk2-config-generator/src/main/java
	at org.jvnet.hk2.config.generator.maven.AbstractConfigGeneratorMojo.internalExecute(AbstractConfigGeneratorMojo.java:113)
	at org.jvnet.hk2.config.generator.maven.AbstractConfigGeneratorMojo.execute(AbstractConfigGeneratorMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :config-types

**Comment by jwells131313** [comment]
What version of the java compiler are you using?

**Comment by puntogil** [comment]
OpenJDK 8
Installed:
   ant-lib.noarch 0:1.9.4-11.fc23                                                
   aopalliance.noarch 0:1.0-9.fc21                                               
   args4j.noarch 0:2.0.30-2.fc22                                                 
   atinject.noarch 0:1-20.20100611svn86.fc23                                     
   bcel.noarch 0:6.0-0.3.20140406svn1592769.fc22                                 
   cdi-api.noarch 0:1.1-9.fc23                                                   
   codemodel.noarch 0:2.6-16.fc23                                                
   easymock.noarch 0:3.3.1-1.fc23                                                
   felix-bundlerepository.noarch 0:1.6.6-17.fc22                                 
   felix-osgi-compendium.noarch 0:1.4.0-20.fc21                                  
   felix-osgi-core.noarch 0:1.4.0-17.fc21                                        
   glassfish-el-api.noarch 0:3.0.0-6.fc23                                        
   google-guice.noarch 0:4.0-1.fc23                                              
   hibernate-validator.noarch 0:5.0.1-4.fc23                                     
   javassist.noarch 0:3.18.1-3.fc23                                              
   junit.noarch 1:4.12-2.fc23                                                    
   jvnet-parent.noarch 0:4-5.fc21                                                
   maven.noarch 0:3.3.3-1.fc23                                                   
   maven-antrun-plugin.noarch 0:1.8-1.fc22                                       
   maven-archiver.noarch 0:2.6-1.fc22                                            
   maven-compiler-plugin.noarch 0:3.3-1.fc23                                     
   maven-local.noarch 0:4.5.0-3.fc23                                             
   maven-osgi.noarch 1:0.2.0-9.fc22                                              
   mockito.noarch 0:1.10.19-1.fc23                                               
   objectweb-asm.noarch 0:5.0.3-1.fc22                                           
   osgi-resource-locator.noarch 0:1.0.1-6.fc23                                   
   springframework-context.noarch 0:3.2.13-4.fc23                                
   testng.noarch 0:6.8.21-1.fc22                                                 
   tiger-types.noarch 0:1.4-6.fc23                                               
 Dependency Installed:
   aether-api.noarch 1:1.0.2-1.fc22                                              
   aether-connector-basic.noarch 1:1.0.2-1.fc22                                  
   aether-impl.noarch 1:1.0.2-1.fc22                                             
   aether-spi.noarch 1:1.0.2-1.fc22                                              
   aether-transport-wagon.noarch 1:1.0.2-1.fc22                                  
   aether-util.noarch 1:1.0.2-1.fc22                                             
   alsa-lib.x86_64 0:1.0.29-1.fc23                                               
   ant.noarch 0:1.9.4-11.fc23                                                    
   ant-antlr.noarch 0:1.9.4-11.fc23                                              
   ant-junit.noarch 0:1.9.4-11.fc23                                              
   antlr-tool.noarch 0:2.7.7-36.fc23                                             
   apache-commons-beanutils.noarch 0:1.9.2-3.fc22                                
   apache-commons-cli.noarch 0:1.2-13.fc21                                       
   apache-commons-codec.noarch 0:1.10-1.fc22                                     
   apache-commons-collections.noarch 0:3.2.1-25.fc22                             
   apache-commons-compress.noarch 0:1.9-2.fc22                                   
   apache-commons-configuration.noarch 0:1.10-4.fc22                             
   apache-commons-digester.noarch 0:2.1-4.fc22                                   
   apache-commons-io.noarch 1:2.4-13.fc22                                        
   apache-commons-jexl.noarch 0:2.1.1-12.fc23                                    
   apache-commons-jxpath.noarch 0:1.3-23.fc23                                    
   apache-commons-lang.noarch 0:2.6-16.fc21                                      
   apache-commons-lang3.noarch 0:3.4-1.fc23                                      
   apache-commons-logging.noarch 0:1.2-3.fc23                                    
   apache-commons-net.noarch 0:3.3-5.fc22                                        
   apache-commons-parent.noarch 0:37-2.fc22                                      
   apache-commons-validator.noarch 0:1.4.0-8.fc21                                
   apache-commons-vfs.noarch 0:2.0-15.fc22                                       
   apache-parent.noarch 0:17-1.fc23                                              
   apache-rat-core.noarch 0:0.11-1.fc23                                          
   apache-rat-plugin.noarch 0:0.11-1.fc23                                        
   apache-resource-bundles.noarch 0:2-15.fc23                                    
   aqute-bndlib.noarch 0:1.50.0-11.fc23                                          
   avalon-framework.noarch 0:4.3-11.fc21                                         
   avalon-logkit.noarch 0:2.1-18.fc23                                            
   base64coder.noarch 0:20101219-12.fc22                                         
   batik.noarch 0:1.8-1.fc23                                                     
   batik-css.noarch 0:1.8-1.fc23                                                 
   bea-stax.noarch 0:1.2.0-10.fc21                                               
   bea-stax-api.noarch 0:1.2.0-10.fc21                                           
   bean-validation-api.noarch 0:1.1.0-3.fc21                                     
   beust-jcommander.noarch 0:1.47-1.fc22                                         
   bsf.noarch 0:2.4.0-20.fc23                                                    
   bsh.noarch 0:1.3.0-32.fc22                                                    
   buildnumber-maven-plugin.noarch 0:1.3-3.fc23                                  
   bytelist.noarch 0:1.0.8-9.fc21                                                
   cglib.noarch 0:3.1-5.fc22                                                     
   classmate.noarch 0:1.1.0-1.fc23                                               
   codehaus-parent.noarch 0:4-8.fc21                                             
   dom4j.noarch 0:1.6.1-22.fc21                                                  
   eclipse-equinox-osgi.x86_64 1:4.5.0-0.18.git201505172000.fc23                 
   felix-osgi-foundation.noarch 0:1.2.0-18.fc21                                  
   felix-osgi-obr.noarch 0:1.0.2-14.fc22                                         
   felix-shell.noarch 0:1.4.3-6.fc21                                             
   felix-utils.noarch 0:1.8.0-1.fc23                                             
   fontconfig.x86_64 0:2.11.93-2.fc23                                            
   fontpackages-filesystem.noarch 0:1.44-11.fc23                                 
   fop.noarch 0:1.1-10.fc23                                                      
   forge-parent.noarch 0:38-3.fc21                                               
   freetype.x86_64 0:2.5.5-1.fc23                                                
   geronimo-annotation.noarch 0:1.0-16.fc21                                      
   geronimo-interceptor.noarch 0:1.0.1-13.fc21                                   
   geronimo-jms.noarch 0:1.1.1-19.fc21                                           
   geronimo-parent-poms.noarch 0:1.6-19.fc21                                     
   geronimo-validation.noarch 0:1.1-12.fc22                                      
   giflib.x86_64 0:4.1.6-12.fc22                                                 
   glassfish-servlet-api.noarch 0:3.1.0-7.fc23                                   
   groovy-lib.noarch 0:2.4.3-3.fc23                                              
   guava.noarch 0:18.0-3.fc23                                                    
   hamcrest.noarch 0:1.3-12.fc23                                                 
   hamcrest-core.noarch 0:1.3-12.fc23                                            
   hawtjni-runtime.noarch 0:1.10-4.fc23                                          
   hibernate-jpa-2.0-api.noarch 0:1.0.1-15.fc22                                  
   hsqldb1.noarch 0:1.8.1.3-6.fc23                                               
   httpcomponents-client.noarch 0:4.4.1-1.fc23                                   
   httpcomponents-core.noarch 0:4.4.1-1.fc23                                     
   httpcomponents-project.noarch 0:7-1.fc22                                      
   isorelax.noarch 1:0-0.16.release20050331.fc21                                 
   jai-imageio-core.noarch 0:1.2-0.15.20100217cvs.fc22                           
   jakarta-commons-httpclient.noarch 1:3.1-21.fc22                               
   jakarta-oro.noarch 0:2.0.8-16.fc21                                            
   jansi.noarch 0:1.11-8.fc23                                                    
   jansi-native.x86_64 0:1.5-8.fc22                                              
   java-1.8.0-openjdk.x86_64 1:1.8.0.45-38.b14.fc23                              
   java-1.8.0-openjdk-devel.x86_64 1:1.8.0.45-38.b14.fc23                        
   java-1.8.0-openjdk-headless.x86_64 1:1.8.0.45-38.b14.fc23                     
   javaewah.noarch 0:0.8.4-3.fc21                                                
   javamail.noarch 0:1.5.2-1.fc23                                                
   javapackages-local.noarch 0:4.5.0-3.fc23                                      
   javapackages-tools.noarch 0:4.5.0-3.fc23                                      
   jaxen.noarch 0:1.1.6-5.fc22                                                   
   jboss-interceptors-1.2-api.noarch 0:1.0.0-2.fc22                              
   jboss-logging.noarch 0:3.1.4-3.fc21                                           
   jboss-parent.noarch 0:11-5.fc23                                               
   jcodings.noarch 0:1.0.9-7.fc21                                                
   jdom.noarch 0:1.1.3-7.fc21                                                    
   jgit.noarch 0:3.7.1-2.fc23                                                    
   jline.noarch 0:2.12.1-1.fc23                                                  
   jna.x86_64 0:4.1.0-7.fc22                                                     
   jsch.noarch 0:0.1.52-1.fc23                                                   
   jsoup.noarch 0:1.8.2-1.fc23                                                   
   jsr-305.noarch 0:0-0.17.20130910svn.fc21                                      
   jtidy.noarch 2:1.0-0.20.20100930svn1125.fc22                                  
   jzlib.noarch 0:1.1.3-2.fc21                                                   
   kxml.noarch 0:2.3.0-7.fc21                                                    
   lcms2.x86_64 0:2.7-1.fc23                                                     
   libICE.x86_64 0:1.0.9-2.fc22                                                  
   libSM.x86_64 0:1.2.2-2.fc22                                                   
   libX11.x86_64 0:1.6.3-1.fc23                                                  
   libX11-common.noarch 0:1.6.3-1.fc23                                           
   libXau.x86_64 0:1.0.8-4.fc23                                                  
   libXext.x86_64 0:1.3.3-2.fc23                                                 
   libXfont.x86_64 0:1.5.1-1.fc23                                                
   libXi.x86_64 0:1.7.4-2.fc23                                                   
   libXrender.x86_64 0:0.9.9-1.fc23                                              
   libXtst.x86_64 0:1.2.2-4.fc23                                                 
   libfontenc.x86_64 0:1.1.3-1.fc23                                              
   libjpeg-turbo.x86_64 0:1.4.0-1.fc22                                           
   libpng.x86_64 2:1.6.17-1.fc23                                                 
   libxcb.x86_64 0:1.11-5.fc23                                                   
   libxslt.x86_64 0:1.1.28-10.fc23                                               
   log4j.noarch 0:2.2-1.fc23                                                     
   log4j12.noarch 0:1.2.17-9.fc22                                                
   lyx-fonts.noarch 0:2.1.3-3.fc23                                               
   maven-artifact.noarch 0:2.2.1-51.fc23                                         
   maven-artifact-manager.noarch 0:2.2.1-51.fc23                                 
   maven-artifact-resolver.noarch 1:1.0-12.fc22                                  
   maven-assembly-plugin.noarch 0:2.5.3-1.fc23                                   
   maven-common-artifact-filters.noarch 0:1.4-15.fc22                            
   maven-dependency-tree.noarch 0:2.2-1.fc22                                     
   maven-doxia-core.noarch 0:1.6-2.fc23                                          
   maven-doxia-logging-api.noarch 0:1.6-2.fc23                                   
   maven-doxia-module-apt.noarch 0:1.6-2.fc23                                    
   maven-doxia-module-fml.noarch 0:1.6-2.fc23                                    
   maven-doxia-module-fo.noarch 0:1.6-2.fc23                                     
   maven-doxia-module-xdoc.noarch 0:1.6-2.fc23                                   
   maven-doxia-module-xhtml.noarch 0:1.6-2.fc23                                  
   maven-doxia-sink-api.noarch 0:1.6-2.fc23                                      
   maven-doxia-sitetools.noarch 0:1.6-1.fc22                                     
   maven-enforcer-api.noarch 0:1.4-1.fc22                                        
   maven-enforcer-plugin.noarch 0:1.4-1.fc22                                     
   maven-enforcer-rules.noarch 0:1.4-1.fc22                                      
   maven-file-management.noarch 1:1.2.1-11.fc22                                  
   maven-filtering.noarch 0:1.3-1.fc22                                           
   maven-invoker.noarch 0:2.2-1.fc23                                             
   maven-jar-plugin.noarch 0:2.6-1.fc23                                          
   maven-javadoc-plugin.noarch 0:2.10.3-1.fc23                                   
   maven-model.noarch 0:2.2.1-51.fc23                                            
   maven-monitor.noarch 0:2.2.1-51.fc23                                          
   maven-parent.noarch 0:26-1.fc22                                               
   maven-plugin-annotations.noarch 0:3.4-2.fc23                                  
   maven-plugin-build-helper.noarch 0:1.9.1-1.fc22                               
   maven-plugin-bundle.noarch 0:2.3.7-14.fc22                                    
   maven-plugin-descriptor.noarch 0:2.2.1-51.fc23                                
   maven-plugin-plugin.noarch 0:3.4-2.fc23                                       
   maven-plugin-registry.noarch 0:2.2.1-51.fc23                                  
   maven-plugin-testing-harness.noarch 0:3.3.0-2.fc23                            
   maven-plugin-tools-annotations.noarch 0:3.4-2.fc23                            
   maven-plugin-tools-api.noarch 0:3.4-2.fc23                                    
   maven-plugin-tools-generators.noarch 0:3.4-2.fc23                             
   maven-plugin-tools-java.noarch 0:3.4-2.fc23                                   
   maven-plugins-pom.noarch 0:27-2.fc22                                          
   maven-profile.noarch 0:2.2.1-51.fc23                                          
   maven-project.noarch 0:2.2.1-51.fc23                                          
   maven-remote-resources-plugin.noarch 0:1.4-9.fc21                             
   maven-reporting-api.noarch 1:3.0-8.fc22                                       
   maven-reporting-impl.noarch 0:2.2-11.fc22                                     
   maven-repository-builder.noarch 1:1.0-1.fc22                                  
   maven-resources-plugin.noarch 0:2.7-2.fc22                                    
   maven-scm.noarch 0:1.9.4-1.fc23                                               
   maven-settings.noarch 0:2.2.1-51.fc23                                         
   maven-shared-incremental.noarch 0:1.1-8.fc22                                  
   maven-shared-io.noarch 1:1.1-11.fc23                                          
   maven-shared-utils.noarch 0:0.7-1.fc22                                        
   maven-source-plugin.noarch 0:2.4-2.fc23                                       
   maven-surefire.noarch 0:2.17-6.fc22                                           
   maven-surefire-plugin.noarch 0:2.17-6.fc22                                    
   maven-surefire-provider-junit.noarch 0:2.17-6.fc22                            
   maven-surefire-provider-testng.noarch 0:2.17-6.fc22                           
   maven-toolchain.noarch 0:2.2.1-51.fc23                                        
   maven-wagon-file.noarch 0:2.9-2.fc23                                          
   maven-wagon-http.noarch 0:2.9-2.fc23                                          
   maven-wagon-http-shared.noarch 0:2.9-2.fc23                                   
   maven-wagon-provider-api.noarch 0:2.9-2.fc23                                  
   mojo-parent.noarch 0:34-2.fc22                                                
   msv-msv.noarch 1:2013.6.1-5.fc23                                              
   msv-xsdlib.noarch 1:2013.6.1-5.fc23                                           
   objectweb-pom.noarch 0:1.5-2.fc21                                             
   objenesis.noarch 0:2.1-1.fc23                                                 
   plexus-archiver.noarch 0:3.0-3.fc23                                           
   plexus-build-api.noarch 0:0.0.7-14.fc23                                       
   plexus-cipher.noarch 0:1.7-9.fc23                                             
   plexus-classworlds.noarch 0:2.5.2-2.fc23                                      
   plexus-cli.noarch 0:1.6-1.fc23                                                
   plexus-compiler.noarch 0:2.4-2.fc23                                           
   plexus-component-api.noarch 0:1.0-0.18.alpha15.fc21                           
   plexus-components-pom.noarch 0:1.3.1-4.fc23                                   
   plexus-containers-component-annotations.noarch 0:1.6-3.fc23                   
   plexus-containers-component-metadata.noarch 0:1.6-3.fc23                      
   plexus-containers-container-default.noarch 0:1.6-3.fc23                       
   plexus-i18n.noarch 0:1.0-0.6.b10.4.fc23                                       
   plexus-interactivity-api.noarch 0:1.0-0.20.alpha6.fc23                        
   plexus-interpolation.noarch 0:1.22-3.fc23                                     
   plexus-io.noarch 0:2.5-2.fc23                                                 
   plexus-pom.noarch 0:3.3.3-1.fc23                                              
   plexus-resources.noarch 0:1.0-0.18.a7.fc23                                    
   plexus-sec-dispatcher.noarch 0:1.4-19.fc23                                    
   plexus-utils.noarch 0:3.0.22-1.fc23                                           
   plexus-velocity.noarch 0:1.1.8-18.fc23                                        
   publicsuffix-list.noarch 0:20150506-1.fc23                                    
   python3-cssselect.noarch 0:0.9.1-5.fc22                                       
   python3-javapackages.noarch 0:4.5.0-3.fc23                                    
   python3-lxml.x86_64 0:3.3.6-1.fc22                                            
   python3-six.noarch 0:1.9.0-1.fc23                                             
   qdox.noarch 0:2.0-0.2.M2.fc23                                                 
   regexp.noarch 1:1.5-18.fc22                                                   
   relaxngDatatype.noarch 0:2011.1-1.fc22                                        
   rhino.noarch 0:1.7R4-10.fc21                                                  
   sisu-inject.noarch 1:0.3.1-1.fc23                                             
   sisu-plexus.noarch 1:0.3.1-1.fc23                                             
   slf4j.noarch 0:1.7.12-1.fc23                                                  
   snakeyaml.noarch 0:1.13-8.fc23                                                
   snappy.x86_64 0:1.1.1-5.fc23                                                  
   snappy-java.noarch 0:1.0.5-2.fc21                                             
   sonatype-oss-parent.noarch 0:7-9.fc21                                         
   springframework.noarch 0:3.2.13-4.fc23                                        
   springframework-aop.noarch 0:3.2.13-4.fc23                                    
   springframework-beans.noarch 0:3.2.13-4.fc23                                  
   springframework-expression.noarch 0:3.2.13-4.fc23                             
   stax2-api.noarch 0:3.1.4-2.fc23                                               
   tomcat-el-3.0-api.noarch 1:8.0.20-1.fc23                                      
   tomcat-servlet-3.1-api.noarch 1:8.0.20-1.fc23                                 
   ttmkfdir.x86_64 0:3.0.9-45.fc23                                               
   tzdata-java.noarch 0:2015d-1.fc23                                             
   velocity.noarch 0:1.7-16.fc22                                                 
   weld-parent.noarch 0:31-1.fc23                                                
   woodstox-core.noarch 0:5.0.0-2.fc23                                           
   ws-jaxme.noarch 0:0.5.2-13.fc23                                               
   xalan-j2.noarch 0:2.7.1-26.fc23                                               
   xbean.noarch 0:4.2-1.fc23                                                     
   xerces-j2.noarch 0:2.11.0-22.fc22                                             
   xml-commons-apis.noarch 0:1.4.01-18.fc21                                      
   xml-commons-resolver.noarch 0:1.2-17.fc21                                     
   xmlgraphics-commons.noarch 0:2.0-1.fc22                                       
   xmlunit.noarch 0:1.6-1.fc22                                                   
   xmvn.noarch 0:2.4.0-2.fc23                                                    
   xmvn-api.noarch 0:2.4.0-2.fc23                                                
   xmvn-connector-aether.noarch 0:2.4.0-2.fc23                                   
   xmvn-core.noarch 0:2.4.0-2.fc23                                               
   xmvn-install.noarch 0:2.4.0-2.fc23                                            
   xmvn-mojo.noarch 0:2.4.0-2.fc23                                               
   xmvn-resolve.noarch 0:2.4.0-2.fc23                                            
   xmvn-subst.noarch 0:2.4.0-2.fc23                                              
   xorg-x11-font-utils.x86_64 1:7.5-28.fc23                                      
   xorg-x11-fonts-Type1.noarch 0:7.5-14.fc22                                     
   xpp2.noarch 0:2.1.10-20.fc23                                                  
   xpp3.noarch 0:1.1.4-5.c.fc23                                                  
   xz-java.noarch 0:1.5-3.fc21

**Comment by puntogil** [comment]
should fixed in https://java.net/jira/browse/HK2-253
https://github.com/hk2-project/hk2/commit/0637b118aa8fc056a705039fc76a46de1da85bc7
