### ISSUE TITLE
Injection of type parameter in a generic class

### ISSUE THREAD

**Issue by fabriziocucci** [hk2-project/hk2#41]
A few days ago, I asked [this](http://stackoverflow.com/questions/40672630/injection-of-type-parameter-in-a-generic-class-with-hk2) question on stackoverflow without success.

I was just wondering whether this is really an issue or something expected.

**Comment by jwells131313** [comment]
Yes I am planning on running your test class when I get some time.

It looks to me like it *should* work.  There have been a few fixes in 
this area since b05 so you might want to try your test again with a 
later version of hk2.

**Comment by fabriziocucci** [comment]
Thanks for your prompt reply @jwells131313 . 

I just tried the same test with hk2-2.5.0-b28 and, unless my code contains some subtle mistake, the result is the same.

**Comment by jwells131313** [comment]
The latest Jersey has picked up 2.5.0-b30 which has this feature
